"""
models/chat.py – Pydantic schemas for conversations and chat messages.

Identity model:
  anonymous_id  → UUID generated by backend on first upload, stored in
                  frontend localStorage. Empty string = not yet assigned.
  user_id       → null until login (future auth). Empty string = not authenticated.

Frontend flow:
  Fresh browser:   anonymous_id = "",  user_id = ""
    → first upload triggers backend to generate UUID anonymous_id
    → returned in UploadInitResponse → frontend stores it

  Returning user:  anonymous_id = "uuid",  user_id = ""
    → backend uses existing anonymous_id

  Logged in:       anonymous_id = "uuid",  user_id = "uuid"
    → backend uses user_id (future)
"""
from __future__ import annotations

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, Field

from models.documents import SourceReference


# ── Conversations ─────────────────────────────────────────────────────────────

class ConversationCreate(BaseModel):
    title: str = "New Chat"
    anonymous_id: str = ""   # empty string = first request, backend generates UUID
    user_id: str = ""        # empty string = not authenticated


class ConversationUpdate(BaseModel):
    title: str


class ConversationResponse(BaseModel):
    conversation_id: UUID
    title: str
    anonymous_id: str | None = None
    user_id: str | None = None
    document_count: int = 0
    total_chunks: int = 0
    message_count: int = 0
    last_message_at: datetime | None = None
    created_at: datetime
    updated_at: datetime

    class Config:
        json_encoders = {UUID: str}


class ConversationListResponse(BaseModel):
    conversations: list[ConversationResponse]
    total: int


# ── Chat Messages ─────────────────────────────────────────────────────────────

class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=4000)
    anonymous_id: str = ""
    document_ids: list[UUID] | None = None
    stream: bool = True


class MessageResponse(BaseModel):
    message_id: UUID
    conversation_id: UUID
    role: str                       # "user" | "assistant"
    content: str
    sources: list[SourceReference] = []
    confidence: str | None = None
    model: str | None = None
    prompt_tokens: int | None = None
    completion_tokens: int | None = None
    latency_ms: int | None = None
    created_at: datetime

    class Config:
        json_encoders = {UUID: str}


class MessageListResponse(BaseModel):
    messages: list[MessageResponse]
    total: int


# ── SSE Stream event payloads ─────────────────────────────────────────────────

class SSETokenEvent(BaseModel):
    type: str = "token"
    content: str


class SSESourcesEvent(BaseModel):
    type: str = "sources"
    sources: list[SourceReference]


class SSEDoneEvent(BaseModel):
    type: str = "done"
    message_id: UUID
    conversation_id: UUID
    confidence: str
    prompt_tokens: int
    completion_tokens: int
    latency_ms: int

    class Config:
        json_encoders = {UUID: str}


class SSETitleEvent(BaseModel):
    """
    Sent as the final SSE event on the first message exchange only.
    Frontend receives this and updates the conversation title in IndexedDB
    and the sidebar simultaneously — no polling needed.
    """
    type: str = "title"
    conversation_id: UUID
    title: str

    class Config:
        json_encoders = {UUID: str}


class SSEErrorEvent(BaseModel):
    type: str = "error"
    message: str


class SSEMetaEvent(BaseModel):
    type: str = "meta"
    conversation_id: UUID
    user_message_id: UUID

    class Config:
        json_encoders = {UUID: str}


# ── Future auth: claim anonymous conversations on login ───────────────────────

class ClaimConversationsRequest(BaseModel):
    anonymous_id: str
    user_id: str
